# vim: set ft=ruby

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

source "https://github.com/CocoaPods/Specs.git"

platform :ios, "10.0"
use_frameworks!

rn_path = "../node_modules/react-native"

target "TestDriverRN063" do
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])
# use_flipper!

  target "TestDriverRN063Tests" do
    inherit! :complete
  end
end

# Force react-native-heap to be built as a static framework.
# Based on comments at https://github.com/CocoaPods/CocoaPods/issues/7428 .
pre_install do |installer|
    pod = installer.pod_targets.find { |p| p.name == 'react-native-heap'}
    def pod.static_framework?
        true
    end
end

post_install do |installer|
# flipper_post_install(installer)
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete('IPHONEOS_DEPLOYMENT_TARGET')
      config.build_settings.delete('TARGETED_DEVICE_FAMILY')
      config.build_settings.delete('SWIFT_VERSION')
      config.build_settings.delete('ARCHS')
    end
  end
end

