require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'TestDriver' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  pod "react-native-heap", path: "../node_modules/@heap/react-native-heap"

  target 'TestDriverTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    flipper_post_install(installer)
    react_native_post_install(installer)

    installer.pods_project.targets.each do |target|
      if target.name == 'React-Core-AccessibilityResources'
        target.remove_from_project
      else
        target.build_configurations.each do |config|
          config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = 'YES'
          config.build_settings.delete('IPHONEOS_DEPLOYMENT_TARGET')
          config.build_settings.delete('TARGETED_DEVICE_FAMILY')
          config.build_settings.delete('SWIFT_VERSION')
          config.build_settings.delete('ARCHS')
        end
      end
    end
  end
end

# Force react-native-heap to be built as a static framework.
# Based on comments at https://github.com/CocoaPods/CocoaPods/issues/7428 .
pre_install do |installer|
  pod = installer.pod_targets.find { |p| p.name == 'react-native-heap'}
  def pod.static_framework?
    true
  end
end